#!/usr/bin/php
<?php
/**
 * @author Oluwatosin Amokeodo <oluwatosin.amokeodo@gmail.com>
 * @package CRUD API
 * * @license MIT http://opensource.org/licenses/MIT
 * @since Version 1.0
 */

if(PHP_SAPI !== 'cli'){
    exit;
}

require_once "init.php";
use App\Controllers\CreateTable;
(new CreateTable())->runMigrations();
